### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [Homini57/PY202309#1]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/dict_and_set
    - 30:Undefined variable 'key'	print("Name: ", key, "/", "average: ", average)
    - 32:Undefined variable 'key'	print("Name: ", key, "/", "average: ", average)
    - 34:Undefined variable 'key'	print("Name: ", key, "/", "average: ", average)
       - key 변수가 없습니다. key 변수를 선언하고 값을 할당해주세요.
- WARNING in challenge/week4/condition
    - 28:Bad indentation. Found 8 spaces, expected 4	        print("Incorrect Input")
        - 들여쓰기를 맞춰주세요.        
- WARNING in challenge/week7/todo
    - 17:Undefined variable 'i'	        task = task_list[i]
    - 18:Undefined variable 'i'	        print(f'{i+1}. {task}')
    - 16:Unused variable 'I'	    for I in range(len(task_list)):
        - for 문에 인덱스는 I (소문자 i) 리스트 탐사를 위한 변수는 i (소문자 i)로 사용되고 있습니다. 소문자 i 로 맞춰주세요.

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week6/function
- Insufficient comments in challenge/week7/todo
- Insufficient comments in practice/week6/function
- Insufficient comments in project/week8/search_engine

**Comment by Homini57** [comment]
#1 issue complete
1. challenge/week3/dict_and_set : assigned correct variable instead of 'key'
2. challenge/week4/condition : indented rightly 4 spaces.
3. challenge/week7/todo : converted 'I' to 'i' to operate normally
4.  challenge/week6/function : added comments in the files
challenge/week7/todo
practice/week6/function
project/week8/search_engine

38f9c9b
